using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

//  â¤ â˜— | â†“ â† â†’ â†‘ _ â€¾ âˆ¨ âˆ§ Â¬ âŠ— â‰¡ â‰¤ â‰¥ âŒƒ âŒ„ âŠ“â‡… âŠ”â‡µ âŠ âŠ â†±â†³ âˆ‘ -no unity â¤’ â¤“ âŒˆ âŒŠ ğŸ€² ğŸ€¸ âŒ› â° â–¸ â–¹ ğŸ ğŸ–± ğŸ’¾ â†• â™º ğŸ’» ğŸ—” ğŸ–§ á¸† â†• â—©â—ªâ¬”â¬•â¬“â¬’â—§â—¨â—°â—±â—²â—³â¯
 
public class TDD_ShortcutInputExampleMono : MonoBehaviour
{
    public TextAsset m_fileToPush;
    public string m_textToPush;

    public string m_focusId;

    public string m_processName;

    public List<WindowIntPtrUtility.ProcessInformation> m_wowProcess;



    [ContextMenu("Refresh")]
    public void RefreshWowProcess()
    {
        WindowIntPtrUtility.FrechWindowWithExactProcessName(in m_processName, out List<WindowIntPtrUtility.ProcessInformation> p, out m_wowProcess);
    }


    public void PushText()
    {
        PushCommandLine(m_textToPush);
    }
    public void PushFile()
    {
        PushCommandLine(m_fileToPush.text);

    }

    public void PushCommandLine(string command) { 

        
      //  Experiment_BoardcastKeyToWow

    }

    void Start()
    {




 /*
 ğŸ—”45646:0-9 //Send Input to frame with id 45646
 ğŸ—”Wow:0-9 //Send Input to registered by user as wow
 ğŸ—”ğŸ”mspaint:0-9 //Make search on a frame call mspaint send to first found
 ğŸ—”ğŸ”ğŸ“¡mspaint:0-9 //Make search on a frame call mspaint send to all found
 ğŸ—”ğŸ“¡Wow:0-9 // Send input to all frame call exactly wow
 ğŸ’»0-9 // Input to the computer 
 â˜•0-9 // Input to JOMI localy on the computer
 ğŸ”ŒğŸ¤–0-9 // Input to USB port robot // Will be use with arduino later on the project

 */

        SendShortCut ("ğŸ’»A", "Should press A as window Input");
        SendShortCut ("ğŸ’»0", "Should press 0 alpha as window Input");
        SendShortCut ("ğŸ’»0", "Should press 0 alpha as window Input"); 
        SendShortCut ("ğŸ—”46542 ğŸ–®B", "Should press 0 alpha as window Input"); 
        SendShortCut ("ğŸ—”ğŸ”Wow ğŸ–®B", "Should press 0 alpha as window Input"); 
        SendShortCut ("ğŸ—”ğŸ”Wow:0 ğŸ–®B", "Should press 0 alpha as window Input");
        SendShortCut ("ğŸ—”ğŸ“•Wow ğŸ–®B", "Should press 0 alpha as window Input");  
        SendShortCut ("ğŸ’¾Bonjour>ğŸ’¬","");  
        SendShortCut ("ğŸ—”ğŸ”Wow:0", "Should press 0 alpha as window Input"); 


        //ğŸ–§ On The know Network
        //ğŸ—”Frame
        //ğŸ’»Computer
        //Ó” Arduino
        //á›’á›¡ Bluetooh keyboard
        // ğŸ“² Android ADB
        //ğŸ–±ğŸMouse
        //âŒ¨ğŸ–® Keyboard   
        //ğŸ’¾Clipboard 
        //ğŸªPermanant clipboard
        //ğŸ—ğŸ—‹ğŸ–¹file direction
        //ğŸ”’ Lock
        //ğŸ”Œ Port USB 
        //ğŸ¹ Midi
        //ğŸ› Midi Knobs
        //ğŸŒ internet
        // ğŸ® xbox
        // ğŸ•¹ Direct Input Controller
        //ğŸ² Random Number

    }

    private void SendShortCut(string v1, string v2)
    {
       

        //bool sendToAll = v1.IndexOf("ğŸ“¡") > -1;
        //bool frameSymbol = v1.IndexOf("ğŸ—”") > -1;
        //if (v1.StartsWith("ğŸ—”"))
        //{

        //}
        //if (v1.StartsWith("ğŸ—”ğŸ“¡"))
        //{

        //}

     //   SendKeyMessageToWindows.
    }

    // Update is called once per frame
    void Update()
    {
        
    }


    private void BroadcastMessageUp(User32PostMessageKeyEnum key)
    {
        for (int i = 0; i < m_wowProcess.Count; i++)
        {
            SendKeyMessageToWindows.SendKeyUpToProcessChildren(key, m_wowProcess[i].GetAsChildren());
            //Debug.Log("Try down " + m_wowProcess[i].m_processId +" - "+ key);
            //Thread.Sleep(100);
        }
    }

    private void BroadcastMessageDown(User32PostMessageKeyEnum key)
    {
        for (int i = 0; i < m_wowProcess.Count; i++)
        {

            SendKeyMessageToWindows.SendKeyDownToProcessChildren(key, m_wowProcess[i].GetAsChildren());
            //Thread.Sleep(100);
        }
    }


    public void BroadcastPastAction()
    {

        for (int i = 0; i < m_wowProcess.Count; i++)
        {

            // SendKeyToWindow.RequestPastAction( m_wowProcess[i].m_processId);
            //Thread.Sleep(100);
        }

    }
}
